### ISSUE TITLE
get instructions

### ISSUE THREAD

**Issue by prasanganath** [justinsalamon/milsed#4]
How run in this project on our local machine. this READ ME does't include it

**Comment by justinsalamon** [comment]
Generally speaking this research code is provided as is and we cannot provide support for it.

That said, if you go into any of the `model_` folders you'll find numbered scripts `00_setup.py`, `01_prepare.py`, etc. Running those scripts in order should, in principle, reproduce the experiments from the paper. But again, we cannot provide further support for this repo at the time.

If you're only looking to use the AutoPool layer, see: https://github.com/marl/autopool

**Comment by prasanganath** [comment]
okk.. thank you for your quickly response
